### PR TITLE
Updates to error messages in U1L1: Using the Random Block

### PR DESCRIPTION
**Pull request by NathanielLow**

### CODE REVIEW

**Comment by NathanielLow** [comment]
Updated to include AG for Traffic Simulator from Unit 5, Lab 6.

**Comment by NathanielLow** [comment]
Updated to include AG for U7_L2_P3 If There Is Time... exercise.

**Comment by NathanielLow** [comment]
Updated to include AG for U7_L3_P4 If There Is Time... exercise.

**Comment by thuangy** [comment]
Thanks Nathaniel!

**Pull request merged**
